### ISSUE TITLE
A small suggestion

### ISSUE THREAD

**Issue by DIYMSG** [arnobpl/SymlinkCreator#16]
This is a great program!  Thanks for making it.
I have a few suggestions to improve it's functionality. 
1. When selecting folders allow it to select multiple folders at once. (right now you have to add 1 by 1)
2. Save history or allow it to import a previous script we saved (maybe importing it is easier to implement?).

**Comment by arnobpl** [comment]
Hello, thank you for using Symlink Creator and sharing the great feedback! I have a plan to implement consolidating file and folder browsers into one so that users can add one or more files or folders. I also consider your feedback for the second one, but it may take some time.

I will keep this one open until the first one (consolidating file and folder browsers) is implemented.

Happy Symlinking!

**Comment by arnobpl** [comment]
I am adding a multi-select folder browser instead of consolidating file and folder browsers as previously mentioned because a consolidated file/folder browser with multi-select is difficult to implement due to a lack of native support from the framework. For the history feature, I have thought about it. I don't have an immediate plan right now. My concern is: adding the history feature will not impact the simplicity of the UI (like having more buttons for more features that may confuse other users).

Finally, thank you again for your great feedback!
