### ISSUE TITLE
SymlinkCreator, some suggestions and ideas

### ISSUE THREAD

**Issue by quasiblob** [arnobpl/SymlinkCreator#19]
**Source file or folder list**
- Could it be possible to allow drag and drop?
  - Like drop a folder from File Explorer would add that path to source list
  - Or drop a file from File Explorer to add a file
  - Now what I do, is I press "Add Files" or "Add folders" and then copy paste the path into the file/folder popup box

**Destination Path**
- Could it be possible to allow copy pasting a path here? Directly into the field in UI
 - I think I've tried it a couple of times, and it doesn't seem to work for me

**Delete selected button**
- This sounds scary and is not what it does 
  - Could you consider renaming this to something like "Remove from list", to make it obvious what it really does

**Popup after operation**
- Super annoying, could there at least be an option to disable this?

**About screen**
- Could you consider making the link in popup a http-link instead of Yes/No box where Yes answer takes you to Github? I find it annoying to accidentally opening some website, when I only want to check which version I'm running.

Sorry if this sounds like a lot of complaints, but anyway - Symlink Creator feels like the best software right now for making symbolic links, out of the ones I've tested. For example, I find the UX of linkMaker really cumbersome, and that one popular copy-paste kind of link maker is similar way quite cumbersome to use, can't even remember its name now.  Your software does the thing right, window stays open after the operation, which is important for me, many times I decide to change either the source or destination path, after which I add another symbolic link. So this flow you have is really suitable at least for me.

Thanks for making this software.

**Comment by arnobpl** [comment]
Thank you for sharing your valuable feedback! I highly appreciate it.

I am taking all your feedback into account for the next revisions of Symlink Creator. However, I want to clarify some of the features mentioned in this issue:

- **Drag-n-drop into source list:** This feature has already been there since the first version (i.e., you can drag and drop files/folders from File Explorer into the source listbox of Symlink Creator). However, the catch is: that due to the security measures enforced by Windows, the drag-n-drop feature does not work if Symlink Creator is run as admin. [See](https://superuser.com/q/59051/243390) for more info.
- **Pasting destination path:** It currently does not work if the path is enclosed by quotes. But it works if there are no quotes in the path. It is annoying! I will fix it in the next version so that Symlink Creator can recognize both forms of the destination path (with and without enclosing quotes). *Bonus: for now, you can drag-n-drop the destination folder into the destination path textfield (of course, Symlink Creator must not be run as admin).*

As I said, I am considering all the feedback to make Symlink Creator even better. The more feedback is shared, the better version of the application will be. I will keep this issue open until I resolve it in the next releases.

Happy Symlinking! :)

**Comment by quasiblob** [comment]
Hi and thank you!

Drag and drop seems to working, I don't know why I had set SymlinkCreator to run as administrator, disabled it and the drag and drop of path works fine for both source and the target fields. It would be super nice if it was possible to tell the user somehow when this happens.

**Comment by arnobpl** [comment]
Yes, I plan to improve user experience so that users do not miss the drag-and-drop feature.
