### ISSUE TITLE
No error message for non existant paths

### ISSUE THREAD

**Issue by olfek** [arnobpl/SymlinkCreator#7]

**Comment by arnobpl** [comment]
Thank you for using Symlink Creator. A visible error message is a good idea.

**Comment by arnobpl** [comment]
The commit 6b594a85925641b0a711c7668278626287645b80 resolves the issue.

**Comment by arnobpl** [comment]
I think, that should be done by user so that Symlink Creator is not doing something unintentional. It may be a typo for incomplete copy-pasting the destination path because drag-n-dropping destination directory should never cause such issue. Also, non-existent path can be arbitrary that may require multiple directory creations (bunch of nested directories). So Symlink Creator can notify the user for a potential path issue so that user can take of the destination path issue.
