### ISSUE TITLE
SymLink Creator 1.2.2 triggering Malware Threat 

### ISSUE THREAD

**Issue by Wolphin5** [arnobpl/SymlinkCreator#8]
When I try to run the executable, it is triggering a threat warning within Windows Defender.

It is giving warning for Trojan:Win32/Sabsik.FL.B!ml and I am not willing to run at this time.  Likely this is a false-positive, but...

**Comment by arnobpl** [comment]
That is a bad news for me! But thank you for raising the concern about security threat raised by Windoes Defender.
I would like to know more about it like which OS version and Windows Defender version are triggering the threat?
Is Windows Defender up-to-date? Or, even a screenshot is helpful. I regularly use this tool and I also use Microsoft security tool that is built into Windows 11. I never faced such alarm. But I want to know more about it so that we can be confident about the usage of the tool.

**Comment by Wolphin5** [comment]
Windows 10 Pro 22H2 (OS Build 19045.2965).  It is the built-in malware protection.

As soon as I tried to run the EXE in https://github.com/arnobpl/SymlinkCreator/releases/download/v1.2.2/Symlink.Creator.1.2.2.zip I got the warning, or when I extracted it, it also triggered.

You may want to look at seeing if it is likely being a false-positive, since it does a) want admin to run, b) runs a command against folders/files.  Not sure exactly how to report it as a false positive.

I also found another project which is also having this issue: https://github.com/marticliment/WingetUI/issues/1116  and it was about the same time I had issues.

Defender is up to date, yes.  KB2267602 (Version 1.391.1646.0 and 1.39116664.0 installed today)

I will give my system a restart when I have a moment tomorrow (as do have pending restart for updates) and see if the issue still happens.

**Comment by arnobpl** [comment]
Thank you for the detailed information. One more thing I would like to check if the ZIP file you downloaded from GitHub is unmodified. I have run mine and here is the result:
```
> certutil -hashfile .\Symlink.Creator.1.2.2.zip SHA256
SHA256 hash of .\Symlink.Creator.1.2.2.zip:
9b736c4a277ec99987d9033da3769c829ec32f78882bcb7a71ec66149eeff90b
CertUtil: -hashfile command completed successfully.
```
You may want to check if the SHA256 value is the same. If it is the same, then I have doubts if Windows 10 and Windows 11 have different anti-virus definitions that Microsoft provides.

I will follow the other issue ticket you have shared since the issue looks similar.

Anyway, thank you again for raising the concern.

**Comment by Wolphin5** [comment]
confirmed the hash matches.  My output is below.
`PS D:\=Installers\_Utilities> certutil -hashfile .\Symlink.Creator.1.2.2.zip SHA256
SHA256 hash of .\Symlink.Creator.1.2.2.zip:
9b736c4a277ec99987d9033da3769c829ec32f78882bcb7a71ec66149eeff90b
CertUtil: -hashfile command completed successfully.`

I will be rebooting tomorrow (just before midnight here) and will follow up...  I work as IT tech, and have seen stranger things than this be fixed by a reboot.

**Comment by Wolphin5** [comment]
Hmmm... it seems the issue is resolved... as it is opening without a malware warning.

**Comment by arnobpl** [comment]
Thank you for providing the update. I am closing the issue because I don't have any action items for it.
